variables:
  GIT_SUBMODULE_STRATEGY: recursive

stages:
  - test_qt5
  - test_qt62_jammy
  - test_qt64

Test_qt5:
  stage: test_qt5
  image:
    name: "carlonluca/qt-dev:5.15.2_dev"
    entrypoint: [""]
  script:
    - mkdir build
    - cd build
    - cmake ../qt5
    - make
    - export QTEST_FUNCTION_TIMEOUT=10000000
    - ./LQtUtilsTest

Test_qt62_jammy:
  stage: test_qt62_jammy
  image:
    name: "carlonluca/qt-dev:6.2.4_jammy"
    entrypoint: [""]
  script:
    - mkdir build
    - cd build
    - cmake ../qt6
    - make
    - export QTEST_FUNCTION_TIMEOUT=10000000
    - ./LQtUtilsTest

Test_qt64:
  stage: test_qt64
  image:
    name: "carlonluca/qt-dev:6.4.1"
    entrypoint: [""]
  script:
    - mkdir build
    - cd build
    - QT_HOST_PATH=/opt/Qt-amd64-6.4.1 cmake ../qt6
    - make
    - export QTEST_FUNCTION_TIMEOUT=10000000
    - ./LQtUtilsTest