variables:
  GIT_SUBMODULE_STRATEGY: recursive

stages:
  - test_qt5
  - test_qt61
  - test_qt62

Test_qt5:
  stage: test_qt5
  image:
    name: "carlonluca/qt-dev:5.15.2"
    entrypoint: [""]
  script:
    - mkdir build
    - cd build
    - cmake ../qt5
    - make
    - ./LQtUtilsTest

Test_qt61:
  stage: test_qt61
  image:
    name: "carlonluca/qt-dev:6.1.2"
    entrypoint: [""]
  script:
    - mkdir build
    - cd build
    - cmake ../qt6
    - make
    - ./LQtUtilsTest

Test_qt62:
  stage: test_qt62
  image:
    name: "carlonluca/qt-dev:6.2.3"
    entrypoint: [""]
  script:
    - mkdir build
    - cd build
    - cmake ../qt6
    - make
    - ./LQtUtilsTest